# cloud-config
# https://coreos.com/os/docs/latest/cloud-config.html

# Set Hostname
hostname: "CTUV56578606C"

# Set SSH Key for core
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCq5MXWzMBr7IU1Hsat6sHl5w3l019EzFMp4Snx8Ssx6ryGi8ngIt1RQrT5Rys7eJIoDrMtPMo4J056ezLvOsTFjeZenj0/dZXe1V1KYT2JhLToEFAQX+b79UusO0pzasUJisVLC5RgMnOgHqUiGnwuuisicjmoF5zB15BqEs+iQpCe7p2DTkA6kyAHkKM3hK3jiv6D0gmREmj6X9nuMeHJOFRsk/g22YpTYMBsy9Na2gn3IyYGrJaZB14Pb9WEJa0oG8KQLEMQ4Puy08GqImezg/c9hu2+CFlPzFZGUqZBS3mthZ2hDzIRf2/s0iU2dz66IoymZcKbVoVc4tIZxFD1"
# add user shadow
users:
  - name: "shadow"
    passwd: "aetwtvlant39t3q0jdbosniers0j"
    groups:
      - "sudo"
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCq5MXWzMBr7IU1Hsat6sHl5w3l019EzFMp4Snx8Ssx6ryGi8ngIt1RQrT5Rys7eJIoDrMtPMo4J056ezLvOsTFjeZenj0/dZXe1V1KYT2JhLToEFAQX+b79UusO0pzasUJisVLC5RgMnOgHqUiGnwuuisicjmoF5zB15BqEs+iQpCe7p2DTkA6kyAHkKM3hK3jiv6D0gmREmj6X9nuMeHJOFRsk/g22YpTYMBsy9Na2gn3IyYGrJaZB14Pb9WEJa0oG8KQLEMQ4Puy08GqImezg/c9hu2+CFlPzFZGUqZBS3mthZ2hDzIRf2/s0iU2dz66IoymZcKbVoVc4tIZxFD1"
        ##############################
        #    No Password Required    #
        #    By Shadow               #
        ##############################

# configure services
coreos:
  update:
    reboot-strategy: "reboot"
  locksmith:
    window-start: Thu 01:00
    window-length: 1h
    # Locksmith supports maintenance window
  
  etcd:
    name:                         shadow-etcd-T1
    listen_client_urls:           https://10.130.226.37:2379
    advertise_client_urls:        https://10.130.226.37:2379
    listen_peer_urls:             https://10.130.226.37:2380
    initial_advertise_peer_urls:  https://10.130.226.37:2380
    initial_cluster:              shadow-etcd-T1=https://10.130.226.37:2380,shadow-etcd-T2=https://10.130.226.38:2380,shadow-etcd-T3=https://10.130.226.39:2380
    initial_cluster_token:        <my-etcd-token>
    initial_cluster_state:        new
    
# define set of files
write-files:
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: "root"
    content: |
      nameserver 10.130.255.161
      nameserver 10.58.38.254
      nameserver 10.33.139.48
      nameserver 218.6.200.139
      nameserver 61.139.2.69
      nameserver 8.8.8.8

# set /etc/hosts make you nslookup 127.0.0.1
manage_etc_hosts: "localhost"
